{
    'name': 'Estates Odoo 18 Modifications',
    'version': '1.1',
    'category': 'Accounting',
    'summary': 'Estates Odoo 18 Modifications',
    'description': 'Estates Odoo 18 Modifications',
    'author': 'Bey Technologies Limited',
    'company': 'Bey Technologies Limited',
    'maintainer': 'Bey Technologies Limited',
    'website': "https://www.beytech.co.tz",
    'depends': ['base','account', 'mail','stock','purchase', 'sale_management',],
    'data': [
        "security/ir.model.access.csv",
        "data/mail_templates.xml",
        "views/res_company.xml",
        "views/accounts_view.xml",
        "views/res_partner.xml",
        "views/sale_order_views.xml",
        "views/sale_report_wizard_views.xml",
        "views/sale_advance_payment_inv_views.xml",

        "views/purcheses.xml",

        # "wizard/create_invoice_from_delivery_wizard_views.xml",

        "reports/report_invoice.xml",
        "reports/report_loading_instruction.xml",
        "reports/report_sale_order_pdf.xml",
        "reports/sales_acknowledgement.xml",
        "reports/report_custom_delivery_note.xml",
    ],
    'images': ['static/description/banner.jpg'],
    'license': 'AGPL-3',
    'sequence': 1,
    'installable': True,
    'auto_install': False,
    'application': True,
}
